#pragma comment(lib,"HIDCtrl_x64.lib") 
extern "C" _declspec(dllimport) int _stdcall GetCtrlLEDCount(void);
extern "C" _declspec(dllimport) int _stdcall PowerLED(int Index, int Status);
extern "C" _declspec(dllimport) int _stdcall GetCtrlCount(void);
extern "C" _declspec(dllimport) int _stdcall PowerOn(int Index);
extern "C" _declspec(dllimport) int _stdcall PowerOnEx(int Index);
extern "C" _declspec(dllimport) int _stdcall PowerOn1(void);
extern "C" _declspec(dllimport) int _stdcall PowerOnEx1(void);
extern "C" _declspec(dllimport) int _stdcall PowerOn2(void);
extern "C" _declspec(dllimport) int _stdcall PowerOnEx2(void);
extern "C" _declspec(dllimport) int _stdcall PowerOff(int Index);
extern "C" _declspec(dllimport) int _stdcall PowerOffEx(int Index);
extern "C" _declspec(dllimport) int _stdcall PowerOff1(void);
extern "C" _declspec(dllimport) int _stdcall PowerOffEx1(void);
extern "C" _declspec(dllimport) int _stdcall PowerOff2(void);
extern "C" _declspec(dllimport) int _stdcall PowerOffEx2(void);
extern "C" _declspec(dllimport) int _stdcall PowerStatus(int Index);
extern "C" _declspec(dllimport) int _stdcall PowerStatus1(void);
extern "C" _declspec(dllimport) int _stdcall PowerStatus2(void);
extern "C" _declspec(dllimport) int _stdcall PowerOn3(void);
extern "C" _declspec(dllimport) int _stdcall PowerOnEx3(void);
extern "C" _declspec(dllimport) int _stdcall PowerOn4(void);
extern "C" _declspec(dllimport) int _stdcall PowerOnEx4(void);
extern "C" _declspec(dllimport) int _stdcall PowerOff3(void);
extern "C" _declspec(dllimport) int _stdcall PowerOffEx3(void);
extern "C" _declspec(dllimport) int _stdcall PowerOff4(void);
extern "C" _declspec(dllimport) int _stdcall PowerOffEx4(void);
extern "C" _declspec(dllimport) int _stdcall PowerStatus3(void);
extern "C" _declspec(dllimport) int _stdcall PowerStatus4(void);
